### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by noamalffasy** [b1naryth1ef/disco#107]
Disco 0.0.12 won't work with python 3.7.

It looks like an issue with the gevent library, based on issue gevent/gevent#1019

gevent 1.3 should fix it

**Comment by Watchful1** [comment]
Any progress on this? Updating gevent to 1.3.6 allowed me to pip install the repo, but then some imports failed. It feels a bit awkward that python 3.7 has been recommended for almost two months now and this package doesn't even install on it.

**Comment by Watchful1** [comment]
I forked the repo, updated gevent to 1.3.6 and changed one of the import names that was failing. But now I'm unable to login. Anyone willing to give this a shot and see if it's just me?

https://github.com/Watchful1/disco

**Comment by Watchful1** [comment]
I think that should do it.

**Comment by Mirdalan** [comment]
@b1naryth1ef it seems that new package was not built and is not available on pypi so the issue still remains on production...

**Comment by osilkin98** [comment]
Yeah, I'm experiencing the same issue as @Mirdalan
