### ISSUE TITLE
Adding a 'ready' listener results in a ReccursionError.

### ISSUE THREAD

**Issue by 4Kaylum** [b1naryth1ef/disco#12]
Regardless of whether the function contains anything, if your code contains a ready listener, it will result in a ReccursionError on line 156 in the `__init__` of `_tblib.py`

    @Plugin.listen('Ready')
    def on_ready(self, event):
        pass

**Comment by b1naryth1ef** [comment]
Hmm, I can't replicate this on master. Can you trying running your code w/ the latest version (whatevers in master now) and see if it happens? Also pasting the traceback would be helpful. For reference, what I did:

```python
class BasicPlugin(Plugin):
    @Plugin.listen('ready')
    def on_ready(self, event):
        print event
```

```
(disco)[andrei@eos:~/code/python/disco]$ python -m disco.cli --token="..." --run-bot --plugin examples.basic_plugin                                                                                                                                       (master!) 
INFO:HTTPClient:GET https://discordapp.com/api/v6/gateway (None)
INFO:GatewayClient:Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json`
INFO:GatewayClient:WS Opened: sending identify payload
INFO:GatewayClient:Recieved HELLO, starting heartbeater...
INFO:GatewayClient:Recieved READY
<disco.gateway.events.Ready object at 0x7fa5d9963050>
```

**Comment by 4Kaylum** [comment]
Having uninstalled and reinstalled Disco via Pip, I can't seem to replicate it either. I probably downloaded an older version somehow. Regardless, it works now. Thanks.
