### ISSUE TITLE
Add ability for Plugin subclasses

### ISSUE THREAD

**Issue by Zwork101** [b1naryth1ef/disco#127]
I want to do things like subclass `Plugin` so all my actual plugins can have the same error handler. Right now, you've have to rewrite this function: https://github.com/b1naryth1ef/disco/blob/master/disco/bot/bot.py#L503

It would be create if we could create a config value that allowed you to blacklist Plugin subclasses, which wouldn't be hard to add. I wouldn't mind writing a PR for it, if I knew it would be reviewed.

**Comment by b1naryth1ef** [comment]
Set an attribute on your subclassed plugin base class; `_shallow = True`. I honestly don't totally remember how this works or why I called it `shallow`, or indeed if it works at all. This was originally added to support exactly your use when I built [rowboat](https://github.com/b1naryth1ef/rowboat/blob/695c6067a84959e9823cba78fef25304a7222ec4/rowboat/plugins/__init__.py#L80).

I'd be more than happy to include a change that makes this more consistent, I think the "proper" way to do it (at least during the time of writing this) would be to add a `register_base_plugin_class()` function to the plugin module (can just append the class to a local list, `_base_plugin_classes`, and then change [this loop](https://github.com/b1naryth1ef/disco/blob/master/disco/bot/bot.py#L502-L507) to ensure classes being loaded do not exist in that list.

**Comment by Zwork101** [comment]
That sounds like a good idea. A pythonic way might be too just create a class decorator, like so:
```py
@plugin_base
class MyPlugin(Plugin):
``` 
Although I'm not sure if older versions of python support this.

**Comment by b1naryth1ef** [comment]
Yeah that was my idea, if its a function with the signature `register_base_plugin_class(cls)` then it could be easily used as a decorator (or otherwise).
