### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by abalbanyan** [b1naryth1ef/disco#13]
"Disco was built to run both as a generic-use library, and a standalone bot toolkit. Installing disco is as easy as running pip install disco-py"

This should probably be "pip install disco.py". I'm very, _very_ embarrassed to say how long this messed me up...

**Comment by b1naryth1ef** [comment]
`disco-py` and `disco.py` should result in the same thing, what version of pip where you on?

**Comment by abalbanyan** [comment]
Oh, this was a mistake on my end! I'm sorry! 
Latest version of pip.
