### ISSUE TITLE
Does this library support voice?

### ISSUE THREAD

**Issue by JavascriptHero** [b1naryth1ef/disco#131]

**Comment by PixeLInc** [comment]
Yes, it supports voice sending and receiving.
Read the source.

There's not really any docs/too much help with receiving but you can always ask in the Discord channel.

**Comment by LMByrne** [comment]
Voice functionallity comes as an optional dependency which needs to be installed using `pip install disco-py[voice]` and there's a basic youtube-dl based music player function example in the [examples folder](https://github.com/b1naryth1ef/disco/blob/master/examples/music.py)

**Comment by jdimpson** [comment]
Could you point me at the source of receiving audio?
