### ISSUE TITLE
Commands arguments with aliases

### ISSUE THREAD

**Issue by aamlima** [b1naryth1ef/disco#14]
When a command has aliases, only the last alias will work with arguments.

Example:
```python
@Plugin.command('help', '<plugin:str>', aliases=['commands', 'foo', 'bar'], description='Show a list of commands.')
```
`help somePluginName`
Bot will reply with `help requires 1 arguments (passed 0)`

`commands somePluginName`
Bot will reply with `commands requires 1 arguments (passed 0)`

`foo somePluginName`
Bot will reply with `foo requires 1 arguments (passed 0)`

`bar somePluginName`
Command will run normally.

**Comment by b1naryth1ef** [comment]
Hey @aamlima, just pushed a fix for this. Mind testing?

**Comment by aamlima** [comment]
Just tested, its working now.
