### ISSUE TITLE
Bounty: Documentation

### ISSUE THREAD

**Issue by b1naryth1ef** [b1naryth1ef/disco#151]
The number one historical issue with Disco has been a lack of quality documentation. This issue mostly stems from my particular disdain with the [Sphinx](http://www.sphinx-doc.org/en/master/) documentation engine and the lack of consistency with docstrings in Python projects. I originally attempted to build [biblio](https://github.com/b1naryth1ef/biblio)--a custom documentation engine--as a solution to this problem, however its still unfinished and would require a decent amount of frontend work to generate high quality documentation.

This issue represents a "bounty" I'm offering to anyone thats interested in picking up the slack and providing a documentation solution which results in automatically generated high quality documentation based on docstrings in the code and a separate set of rich text (in some markdown format) prose/instructional content. The following requirements apply:

- Existing docstrings should be made consistent with whatever docstring format is required. No new documentation needs to be added.
- Documentation generation should be scriptable in our CI environment (travis right now).
- The output should be a human readable HTML website with a modernish/simplistic design (not utilizing proprietary assets).
- Work should be based off the `staging/v1.0.0` branch.

Since Disco is a relatively small project thats entirely maintained by me I'm looking to offer a very-mediocre (but hopefully semi-inspiring) 150$ (US)* bounty towards this goal. As an alternative I'd be willing to offer a negotiable amount of my personal time for another open source project, reviewing code, or otherwise consulting with you. The bounty is at the end of the day up to my discretion. Feel free to reach out to me in our Discord channel if you'd like more clarification or any other questions answered.

*_I'd be paying out via Paypal (or to a charity of your choice), if that doesn't work we'll have to negotiate something else separately_

**Comment by Zwork101** [comment]
Is this bounty still available, and also do you care what documentation engine is used? Biblio looks cool but at the moment seems like a WIP, so I presume you'd want to use something else.

**Comment by b1naryth1ef** [comment]
Its still available, I have no opinions about the documentation engine used, although I'd want to review and understand its community usage to make sure we're not diverging from standard choices for no reason.

**Comment by Zwork101** [comment]
I can't find the staging/v1.0.0 branch locally despite my efforts, so I'm going to work off feature/docs unless I should base off another branch

**Comment by b1naryth1ef** [comment]
You probably half to refetch the origin locally, its here: https://github.com/b1naryth1ef/disco/tree/staging/v1.0.0
