### ISSUE TITLE
PY3/General Issues

### ISSUE THREAD

**Issue by Confuseh** [b1naryth1ef/disco#16]
With current version there are couple problems when it comes to the PY3
- [disco/types/channel.py:301](https://github.com/b1naryth1ef/disco/blob/2bac9f978105454a38f750d20004412ea11410e6/disco/types/channel.py#L301) in py2 `map` returns list, whereas in py3 it returns a generator
- With python3.6, `gevent` has to be updated to 1.2.0 or above, and most of the time `requests[security]` is required or SSLContext ends up in infinite recursion when using gevent monkey patches
- [disco/types/base.py:221](https://github.com/b1naryth1ef/disco/blob/2bac9f978105454a38f750d20004412ea11410e6/disco/types/base.py#L221) It is possible that `obj` argument is `None` therefore an exception occurs since `bytes` does not accept `NoneType`
- Plugin `reload` simply doesn't work, I think it is because module is in the stack, expecting a return from Bots `reload_plugin`, so when attempting to reload module - it fails to reload it. Spawning a separate greenlet for it seems to work though since it returns immediately.

**Comment by b1naryth1ef** [comment]
First 3 are fixed, I'm not sure what you mean by the last? Tested and reloading seems to work fine.

**Comment by Confuseh** [comment]
Thanks for resolving the issues, and that's odd. I'll have another look about `reload` but it wouldn't work for me as in the changes in the file wouldn't be in effect after reloading. I guess time to close it. 👍
