### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by Wumpotamus** [b1naryth1ef/disco#170]
Hi, I was looking to use this library, but it doesn't support Python 3.8, due to gevent still being on 1.3. I would've bumped the version up to 1.5 in a PR, which is what supports 3.8, but that version of gevent is still in an alpha stage. Every other dependency works out of the box, from what I can tell.

**Comment by b1naryth1ef** [comment]
We'll wait for gevent 1.5 to stabilize and then upgrade.
