### ISSUE TITLE
new discord API

### ISSUE THREAD

**Issue by casperdcl** [b1naryth1ef/disco#180]
- discordapp.com is being replaced with discord.com on 2020-11-07
  - https://discord.com/developers/docs/reference implies https://discord.com/api/v6 rather than https://discordapp.com/api/v7
- cdn.discordapp.com is remaining as-is though

**Comment by EpocDotFr** [comment]
Disco is an awesome piece of software, I built a bot full of capabilities thanks to this library. I would be sad Disco to stop functioning just because of a domain update 😢

**Comment by EpocDotFr** [comment]
@b1naryth1ef Is there any plan to release a new version on PyPI? 🤗
