### ISSUE TITLE
Is this still maintained/developed?

### ISSUE THREAD

**Issue by TZer0** [b1naryth1ef/disco#185]
Hey, I was working with this library and I noticed that permission-parsing is completely missing.

This seems like a rather glaring flaw so I was wondering if this library should maybe be marked as unmaintained in the readme so that people are aware of this fact. This is after all something that makes the library unsuited for deployment outside of situations where it is running in the guilds of the bot's developer.

**Comment by b1naryth1ef** [comment]
Can you elaborate on what you mean by permission parsing?

**Comment by TZer0** [comment]
Sure, I'm talking about this: https://github.com/b1naryth1ef/disco/blob/master/disco/types/permissions.py#L121

There doesn't seem to be any way to check what permissions a specific user has?

**Comment by Rapptz** [comment]
That method is overridden by the different concrete implementations such as [`Guild`](https://github.com/b1naryth1ef/disco/blob/7a2e86a2a3dc58e207d2c6e9a686a3296d652864/disco/types/guild.py#L350) or [`Channel`](https://github.com/b1naryth1ef/disco/blob/7a2e86a2a3dc58e207d2c6e9a686a3296d652864/disco/types/channel.py#L151).

**Comment by TZer0** [comment]
Ok, in that case I'm making a PR later today so that it actually tells you how it is done.

**Comment by TZer0** [comment]
https://github.com/b1naryth1ef/disco/pull/186
