### ISSUE TITLE
V1

### ISSUE THREAD

**Issue by b1naryth1ef** [b1naryth1ef/disco#24]
At this point, disco is approaching a stable and mature lib fairly quickly. Both myself and Discord as a company utilize disco for bots we run, and so far the results have shown disco to be rather stable. This issue will serve as a meta-point of the last few things required to really get disco into a stable v1 phase.

- [ ] Full, searchable, easily readable, pretty documentation
- [ ] Cleanup interface naming
- [ ] More testing around non-API components (storage, command parsing, etc)
- [ ] Cleanup performance
- [ ] Cleanup configuration

I'm sure there will be some more minor things required to get this out the door, but that list was whats on the top of my mind.

**Comment by JavascriptHero** [comment]
Very good nani

**Comment by JavascriptHero** [comment]
You should add the ability to create store channels.

guild.createStoreChannel("my game");

**Comment by PixeLInc** [comment]
I feel like that should be a separate issue. BUT, you can already do that.

You can use either `client.api.guilds_channels_create`
or
`guild.create_channel` using type 6. 

You can also make a pr adding the relevant methods and what not.

**Comment by b1naryth1ef** [comment]
I'm adjusting the priorities a bit since this has been sitting open for almost two years. Right now my goals for v1 are now;

- [ ] Holster Removal (#132)
- [ ] New voice engine (pending work)
- [ ] Remove Storage (pending work)
- [ ] Port documentation off biblio onto something else
- [ ] Figure out a better release lifecycle process (changelog, etc)

**Comment by Zwork101** [comment]
Actually, I don't think removing storage is necessary. Right now it's kinda broken yes, however I believe it's a good idea and separates disco-py from other discord libraries. Might I suggest we refactor it instead, with 2 ideas in mind. The idea consists of making sure the interface is simple to use, however connects people to the data on a low level. Secondly, the backend should be interchangeable, like let's say the default is json. I can then create my own MongoDB backend or use someone else's, and just plug that into the storage interface.
