### ISSUE TITLE
Not getting messages in a guild?

### ISSUE THREAD

**Issue by KowalskiThomas** [b1naryth1ef/disco#25]
Hi

I'm trying to use your module, though I'm running through a lot of trouble. I'm using your example code from the home page, but my bot only answers to commands in DMs, not on the guild I added him (he's currently online, but doesn't answer to `ping`). Did I miss something?

Thanks

**Comment by b1naryth1ef** [comment]
Without more information on your configuration and a runtime log its hard to say what the issue is.
