### ISSUE TITLE
Python 3, voice, and StringIO

### ISSUE THREAD

**Issue by Emzi0767** [b1naryth1ef/disco#28]
When trying to use voice in Python 3 (3.6.0, Windows 10 Pro CU, x64), I ran into a problem.

```
...snip...
  File "C:\Users\<me>\AppData\Local\Programs\Python\Python36\lib\site-packages\disco\voice\playable.py", line 17, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

Apparently caused by this code block:

```py
try:
    from cStringIO import cStringIO as StringIO
except:
    from StringIO import StringIO
```

I Googled the problem, and it turned up that `StringIO.StringIO` itself is not available in Python 3. Instead, it was moved to `io` package (so it's `io.StringIO` in py3). The solution is apparently nesting this one step further, however further research shows that it might lead to issues (`str` vs `bytes`). The solution I came up with is:

```py
try:
    from cStringIO import cStringIO as StringIO
except:
    try:
        from StringIO import StringIO
    except:
        from io import StringIO
```

However due to earlier mentioned implications and my limited Python experience, I am not certain whether I can just throw that in without breaking anything.

**Comment by sedruk** [comment]
i had already pointed out this awhile back and it is fixed. but you'll need to install from github
`pip install git+https://github.com/b1naryth1ef/disco@master`

**Comment by Emzi0767** [comment]
Roger. Thanks.
