### ISSUE TITLE
user.get_avatar_url() returns a broken URL?

### ISSUE THREAD

**Issue by XNBlank** [b1naryth1ef/disco#29]
I noticed that when I used this function, the returned URL would have extra characters. An example is this one. 

```
https://cdn.discordapp.com/avatars/68847303431041024/b'7cea5b05de921120b246094cde6272a6'.webp?size=256
```

For some reason there is an extra `b` and `'` characters in the avatar id string. If you tried that URL it would lead to a cloudflare "Bad Gateway" page. It really should be this.

```
https://cdn.discordapp.com/avatars/68847303431041024/7cea5b05de921120b246094cde6272a6.webp?size=256
```

and to temporarily get around it, I had to do this.

```python
embed.set_thumbnail(url=member.user.get_avatar_url(fmt='png', size=256).replace("b'","").replace("'",""))
```
Not sure if this was just me. 🤔

**Comment by Emzi0767** [comment]
It looks as though a string is converted improperly somwhere (`b''` indicates a byte string in python).

**Comment by b1naryth1ef** [comment]
Should be fixed in master, pls give it a try and tell me if you hit anything else @XNBlank

**Comment by XNBlank** [comment]
It's fixed. Thanks b1nzy. 👌
