### ISSUE TITLE
@everyone role is not included in GuildMember.roles

### ISSUE THREAD

**Issue by crudites** [b1naryth1ef/disco#30]
... which would make perfect sense since *everyone* by definition has this role, except that when [computing permissions for a channel](https://github.com/b1naryth1ef/disco/blob/master/disco/types/channel.py#L160), any overwrites for `@everyone` are not taken into account.

I did some digging of my own, and discovered that the official API does not include the `@everyone` role in its responses [despite the documentation not saying anything about it](https://discordapp.com/developers/docs/resources/guild#get-guild-member), and from what I have read so far on this library, it appears that [the library simply takes what the official API gives](https://github.com/b1naryth1ef/disco/blob/master/disco/types/guild.py#L387).

A quick solution would be to take `@everyone` into account when computing permissions, except that other problems may arise from the absence of `@everyone` in `GuildMember.roles`. Another solution would be to not only fix the way permissions are computed for a channel, but also to warn the oblivious developer using the library that `@everyone` is absent from a member's list of roles.

I did not issue a Pull Request as I am not familiar enough (yet) with the library to make careful changes.

**Comment by b1naryth1ef** [comment]
Yeah this is a hold-over from the way I built dscord (which inherently includes the everyone role in the role ids list). Should be pretty easy to fix, I'll take a look this evening.

**Comment by crudites** [comment]
Thank you ❤️
