### ISSUE TITLE
PluginConfig not found

### ISSUE THREAD

**Issue by LiquidPL** [b1naryth1ef/disco#58]
I get an ImportError when trying to import `PluginClass`:

`responder.py`:
```
from disco.bot import Plugin, PluginConfig

class ResponderPluginConfig(PluginConfig):
    var1 = 'test'

@Plugin.with_config(ResponderPluginConfig)
class ResponderPlugin(Plugin):
    @Plugin.command('ping')
    def on_ping_command(self, event):
        event.msg.reply('pong!')
```

```
  File ".../plugins/responder.py", line 1, in <module>
    from disco.bot import Plugin, PluginConfig
ImportError: cannot import name 'PluginConfig'
```
I can't seem to find it anywhere in the code either.

**Comment by slice** [comment]
You should be using the regular `Config` class (from `disco.bot`/`disco.util.config`) for this, just like how [B1nzy is using it here.](https://github.com/b1naryth1ef/b1nb0t/blob/master/b1nb0t/plugins/blob.py#L82)

It looks like some documentation is outdated.

**Comment by LiquidPL** [comment]
Yep, it should be updated. Gonna keep this open then.
