### ISSUE TITLE
event instances but no access to CommandEvent class

### ISSUE THREAD

**Issue by KillyMXI** [b1naryth1ef/disco#63]
I'm using vscode. It has this quirk, not sure about other IDEs. But I guess if it was common practice than vscode Python plugin would've taken it into account too.

I can write
```
from disco.bot import CommandEvent
```
but intellisense does not show `CommandEvent` there. And pylint can't see it either (flake8 can).
(UPD: python 3.4.3. Got `ImportError: cannot import name 'CommandEvent'`.)

Then, if I write
```
class SimplePlugin(Plugin):
    @Plugin.command('ping')
    def on_ping_command(self, event: CommandEvent):
        event.msg.reply('Pong!')
```
I have no autocompletion for `event` object properties and to type information popup.

As a workaround, I can write
```
from disco.types.message import Message

class SimplePlugin(Plugin):
    @Plugin.command('ping')
    def on_ping_command(self, event):
        msg = event.msg  # type: Message
        msg.reply('Pong!')
```
and get autocompletion and type information for `msg` at least.

The reason is that Python plugin for vscode does not look for imports and types information any further than `__all__` in `__init__.py`, and there is no CommandEvent there. This behaviour can be considered questionable, but they might have their reasons too. Performance, for example.

I think it would be better design for disco.py itself if all the objects accessible to programmer will have classes properly accessible too.

UPD: I wrote all of this without actually running my code, relying only on IDE response. After getting ImportError on start, it's all more significant now.

**Comment by b1naryth1ef** [comment]
All the things you should import from `disco.bot` are contained with the `__all__` array for that file. I'm guessing there are older examples sitting around that have more egregious imports, but thats a documentation issue.
