### ISSUE TITLE
Voice

### ISSUE THREAD

**Issue by b1naryth1ef** [b1naryth1ef/disco#7]
One of the big remaining tasks for me to feel comfortable moving disco out of the "early alpha" phase is a proper voice implementation. Me and @jhgg have talked in length about this, and thrown some ideas around, but I think the best path forward is to just take stab at it and try to figure out the sharp edges as we go.

**Comment by developerCodex** [comment]
Hello, @b1naryth1ef. Me and the Contributors have deleted the respo containing "PYCord"
