### ISSUE TITLE
Tutorial cli error

### ISSUE THREAD

**Issue by rain2reign** [b1naryth1ef/disco#83]
Whenever i try to connect the bot using [the guidelines from the tutorial](https://b1naryth1ef.github.io/disco/bot_tutorial/first_steps.html), i get this error. At first it was a invalid token, fixed that by regenerating a new token, but now i get this error.  Is there something i am missing or overlooking?

Windows 10 Pro
Disco-py =  v0.0.12rc4

>(everdream-env) PS C:\Users\Faraash> python -m disco.cli --config config.json 
[INFO] 2018-02-11 15:54:04,566 - HTTPClient:271 - GET https://discordapp.com/api/v7/gateway (None)
[INFO] 2018-02-11 15:54:04,983 - GatewayClient:147 - Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream`
[INFO] 2018-02-11 15:54:05,294 - GatewayClient:212 - WS Opened: sending identify payload
[INFO] 2018-02-11 15:54:05,295 - GatewayClient:122 - Received HELLO, starting heartbeater...
[INFO] 2018-02-11 15:54:05,413 - GatewayClient:247 - WS Closed: [4004] Authentication failed. (1)
[INFO] 2018-02-11 15:54:05,413 - GatewayClient:257 - Will attempt to reconnect after 5 seconds
[INFO] 2018-02-11 15:54:10,413 - GatewayClient:147 - Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream`
[INFO] 2018-02-11 15:54:10,707 - GatewayClient:212 - WS Opened: sending identify payload
[INFO] 2018-02-11 15:54:10,707 - GatewayClient:122 - Received HELLO, starting heartbeater...
[INFO] 2018-02-11 15:54:10,831 - GatewayClient:247 - WS Closed: [4004] Authentication failed. (2)
[INFO] 2018-02-11 15:54:10,831 - GatewayClient:257 - Will attempt to reconnect after 10 seconds
[INFO] 2018-02-11 15:54:20,832 - GatewayClient:147 - Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream`
[INFO] 2018-02-11 15:54:21,169 - GatewayClient:212 - WS Opened: sending identify payload
[INFO] 2018-02-11 15:54:21,174 - GatewayClient:122 - Received HELLO, starting heartbeater...
[INFO] 2018-02-11 15:54:21,317 - GatewayClient:247 - WS Closed: [4004] Authentication failed. (3)
[INFO] 2018-02-11 15:54:21,318 - GatewayClient:257 - Will attempt to reconnect after 15 seconds
[INFO] 2018-02-11 15:54:36,318 - GatewayClient:147 - Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream`
[INFO] 2018-02-11 15:54:36,619 - GatewayClient:212 - WS Opened: sending identify payload
[INFO] 2018-02-11 15:54:36,619 - GatewayClient:122 - Received HELLO, starting heartbeater...
[WARNING] 2018-02-11 15:54:36,620 - GatewayClient:88 - Received HEARTBEAT without HEARTBEAT_ACK, forcing a fresh reconnect
[ERROR] 2018-02-11 15:54:36,736 - websocket:53 - close status: 4000
[INFO] 2018-02-11 15:54:36,737 - GatewayClient:247 - WS Closed: [None] None (4)
[INFO] 2018-02-11 15:54:36,737 - GatewayClient:257 - Will attempt to reconnect after 20 seconds
[INFO] 2018-02-11 15:54:56,737 - GatewayClient:147 - Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream`
[INFO] 2018-02-11 15:54:57,023 - GatewayClient:212 - WS Opened: sending identify payload
[INFO] 2018-02-11 15:54:57,024 - GatewayClient:122 - Received HELLO, starting heartbeater...
[INFO] 2018-02-11 15:54:57,154 - GatewayClient:247 - WS Closed: [4004] Authentication failed. (5)
[INFO] 2018-02-11 15:54:57,155 - GatewayClient:257 - Will attempt to reconnect after 25 seconds
[INFO] 2018-02-11 15:55:22,156 - GatewayClient:147 - Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream`
[INFO] 2018-02-11 15:55:22,461 - GatewayClient:212 - WS Opened: sending identify payload
[INFO] 2018-02-11 15:55:22,462 - GatewayClient:122 - Received HELLO, starting heartbeater...
[INFO] 2018-02-11 15:55:22,584 - GatewayClient:247 - WS Closed: [4004] Authentication failed. (6)
Traceback (most recent call last):
  File "S:\Faraash\Documents\Everdream\everdream-env\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "S:\Faraash\Documents\Everdream\everdream-env\lib\site-packages\holster\emitter.py", line 72, in __call__
    return self.callback(*args, **kwargs)
  File "S:\Faraash\Documents\Everdream\everdream-env\lib\site-packages\disco\gateway\client.py", line 250, in on_close
    raise Exception('Failed to reconnect after {} attempts, giving up'.format(self.max_reconnects))
Exception: Failed to reconnect after 5 attempts, giving up
Sun Feb 11 15:55:22 2018 <Greenlet at 0x21f7445e768: <holster.emitter.EmitterSubscription object at 0x0000021F7446D6D8>(4004, 'Authentication failed.')> failed with Exception

**Comment by MrLotU** [comment]
Windows is not supported by Disco, so there's no way to fix this issue other than swap over to Linux or MacOS

**Comment by rain2reign** [comment]
Must have overlooked that memo somewhere, well that's not a deal breaker for me. 👍 
Than i just swap over to my laptop device which has a linux distro. :)
