### ISSUE TITLE
MessageUpdate not sending a full message object

### ISSUE THREAD

**Issue by Alkali-Metal** [b1naryth1ef/disco#84]
Hey, so when I have the bot return a response with an embed. It triggers both the `MessageCreate` and `MessageUpdate` gateway events.

Which when triggering the `MessageUpdate` event, it sends a message object with the `event.message.author.bot` attribute being `False` (bypassing the bot ignoring) and then when you call the the `get_commands_for_message()` function, it returns [this](https://gist.github.com/Alkali-Metal/cc4c02491d8561d01cc81854c54300b5 "Gist") error, which means that the message object that the bot is sending to the `MessageUpdate` listeners isn't complete from my knowledge. I have no idea how this would be fixed on my end if it is something that I have caused.

(Thanks for such an awesome library btw)

**Comment by b1naryth1ef** [comment]
Can you give an example of the embed your sending? I can definitely see how command parsing for MessageUpdate's is broken, I never spent a lot of time on that and generally people have it disabled.

**Comment by Alkali-Metal** [comment]
Here is some code which reproduces the problem that you can just use as a plugin to test with:

```py
from disco.bot import Plugin
from disco.types.message import MessageEmbed


class MiscCommands(Plugin):

    @Plugin.command("test")
    def test_command(self, event):
        embed = MessageEmbed()
        embed.title = "Embed Title"
        embed.description = "Embed Description"
        embed.set_footer(text="Embed Footer")
        embed.color = None
        
        content = "Response Embed:"

        event.msg.reply(content, embed=embed)
    

    @Plugin.listen("MessageCreate")
    def message_create(self, event):
        print("---MessageCreate---")
        print(event.message.author.bot)
        commands = self.bot.get_commands_for_message(
            False,
            {},
            "~",
            event.message
        )
        print(commands)


    @Plugin.listen("MessageUpdate")
    def message_update(self, event):
        print("---MessageUpdate---")
        print(event.message.author.bot)
        commands = self.bot.get_commands_for_message(
            False,
            {},
            "~",
            event.message
        )
        print(commands)
```

**Comment by b1naryth1ef** [comment]
So while I do think there was a bug, re-reading this it's not related to what your doing. MessageUpdate's are not guaranteed to have the full set of `Message` data, so this is expected behavior. You should double check to make sure that the message update has a valid user and content before trying to pass it through `get_commands_for_message`.
