### ISSUE TITLE
Update Comparison Page in Github Wiki.

### ISSUE THREAD

**Issue by Alkali-Metal** [b1naryth1ef/disco#85]
Update the comparison page in the wiki page so that `discord-py` has the `Autosharding` as a check mark. (rather than an `X`) since It now does actually have auto-sharding.

Also, maybe not needed, but it might be nice if you would allow other users to edit the wiki as then we can keep that stuff updated without needing to bother you. (As I know you can be quite busy at times, and it can always be nice to have a few helpers keep some stuff up-to-date on the documentation side of things)

**Comment by SpencerSharkey** [comment]
The wiki should be nuked in favor of the [disco github.io page](https://b1naryth1ef.github.io/disco/) honestly.

**Comment by Alkali-Metal** [comment]
Yeah, that would probably be best in the long haul.

**Comment by b1naryth1ef** [comment]
Deleted.
