### ISSUE TITLE
Permission Calculation Error With Channel Overwrites

### ISSUE THREAD

**Issue by Alkali-Metal** [b1naryth1ef/disco#98]
When accessing the bot's permissions via, the `embed_links` permission value seems broken as by doing this:
```py
from disco.bot import Plugin

class TestingPlugin(Plugin):
    @Plugin.listen("MessageCreate")
    def message_create_event(self, event):
        print(event.message.channel.get_permissions(
            self.state.me
        ).can(
            16384 # permission value for `embed_links`
        ))
```
It returns the following states after getting the permissions calculation, the output is as follows, taking into account the different permission areas that could happen
```
Guild Base Permission + Channel Overwrite  =  Output
False + (Denied, Neutral)  =  False (As expected)
False + Allowed  =  True (As expected)
True + (Neutral, Allowed)  =  True (As expected)
True + Denied  =  True (Uh oh, that should be overwritten to False)
```
so, is there something happening here on Discord's end but I don't think so as it seems to be pretty consistent with getting the other permission values. I haven't tested all of them, but embed links is the one I've encountered having this problem.

</br></br></br></br>

(note: PixeL also has a similar problem when using the code snippet:
```py
bot_perms = event.channel.get_permissions(self.state.me.id)
if bot_perms.administrator or bot_perms.embed_links:
```
)

**Comment by Zwork101** [comment]
Same issue

**Comment by Zwork101** [comment]
I've been looking around. I think it has to do with this line:
https://github.com/b1naryth1ef/disco/blob/master/disco/types/channel.py#L78
When you do this operation, it will always end up with 0. Not 100% what the point of compiled even is.
This compiled property is then used a lot, which we know is wrong. I can make a PR, but if someone else wants to that's fine.

**Comment by Alkali-Metal** [comment]
If you want to make the PR that is fine by me.

**Comment by b1naryth1ef** [comment]
I believe this is fixed by 75b60b6, but I didn't include tests there since its a bit of legwork to get things going (which impedes on the time I don't have right now to maintain stuff). It'd be great if one of ya'll had some time to test that commit and confirm whether it fixes the issue for you or not (or perhaps even PR some tests :smiley:)

**Comment by Alkali-Metal** [comment]
I'll do some testing of it and get back to you about it. And possibly write some tests depending on how much time I get for it.

**Comment by jlu5** [comment]
With the newest disco master, I got slightly different issues:

- When I have a permission that is TRUE for the guild and NEUTRAL for the channel, `channel.get_permissions()` returns False for any UID and permission (even when I'm the server owner!).
- When I have a permission that is TRUE for the guild and FALSE for the channel, disco hits a TypeError when calculating permissions:

```
2019-02-11 22:57:18,555 [INFO] (discord) bursting guild 497939890063802369/OVD-NET
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/pylink/.local/lib/python3.5/site-packages/holster/emitter.py", line 72, in __call__
    return self.callback(*args, **kwargs)
  File "/home/pylink/.local/lib/python3.5/site-packages/disco_py-0.0.13rc2-py3.5.egg/disco/bot/plugin.py", line 335, in dispatch
    result = func(event, *args, **kwargs)
  File "/home/pylink/pylink-discord/protocols/discord.py", line 169, in on_server_connect
    self._burst_guild(event.guild)
  File "/home/pylink/pylink-discord/protocols/discord.py", line 73, in _burst_guild
    self._burst_new_client(guild, member, pylink_netobj)
  File "/home/pylink/pylink-discord/protocols/discord.py", line 130, in _burst_new_client
    channel_permissions = channel.get_permissions(member)
  File "/home/pylink/.local/lib/python3.5/site-packages/disco_py-0.0.13rc2-py3.5.egg/disco/types/channel.py", line 176, in get_permissions
    denies |= overwrite.deny
TypeError: unsupported operand type(s) for |=: 'int' and 'PermissionValue'
2019-02-12T06:57:18Z <Greenlet "Greenlet-0" at 0x7f8e55a55e48: <holster.emitter.EmitterSubscription object at 0x7f8e55a34240>(<disco.gateway.events.GuildCreate object at 0x7f8e)> failed with TypeError
```

From my own (quick) testing, I believe the two referenced commits above fix the issue.
